[package]
name = "p2p_chat"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
async-std = "1.10.0"
libp2p = { version = "0.54.1", features = ["tcp-async-io", "mdns", "request-response"] }
